"""empty message

Revision ID: 0cc2676b1df7
Revises: 1e85d2914eee
Create Date: 2021-08-12 23:32:41.555606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc2676b1df7'
down_revision = '1e85d2914eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar', sa.Column('nfe', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar', 'nfe')
    # ### end Alembic commands ###
