"""empty message

Revision ID: 0fe86f182a1c
Revises: 0cc2676b1df7
Create Date: 2021-08-12 23:38:17.603667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe86f182a1c'
down_revision = '0cc2676b1df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_a_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_a_pagar', sa.Date(), nullable=False),
    sa.Column('data_pago', sa.DateTime(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas_a_receber')
    # ### end Alembic commands ###
