"""usuario_endereco

Revision ID: 176202e126bc
Revises: 3a8bace32bf0
Create Date: 2021-08-12 13:24:15.663364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176202e126bc'
down_revision = '3a8bace32bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario_nao_registrado', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('usuario_nao_registrado', 'telefone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario_nao_registrado', 'telefone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario_nao_registrado', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
