"""empty message

Revision ID: 1900c783879f
Revises: 61454c551d4b
Create Date: 2021-08-17 08:23:11.269831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1900c783879f'
down_revision = '61454c551d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contrato_usuario_usuario_id_fkey', 'contrato_usuario', type_='foreignkey')
    op.drop_column('contrato_usuario', 'usuario_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato_usuario', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('contrato_usuario_usuario_id_fkey', 'contrato_usuario', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
