"""empty message

Revision ID: 1e85d2914eee
Revises: 8465ca5e96d6
Create Date: 2021-08-12 23:31:56.399592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e85d2914eee'
down_revision = '8465ca5e96d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_a_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_digitado', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_a_pagar', sa.Date(), nullable=False),
    sa.Column('n_documento', sa.String(length=150), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas_a_pagar')
    # ### end Alembic commands ###
