"""empty message

Revision ID: 3312007d7c74
Revises: bc8f2c510cab
Create Date: 2021-08-15 22:23:36.158567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3312007d7c74'
down_revision = 'bc8f2c510cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_endereco', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('usuario_endereco', sa.Column('contrato_usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario_endereco', 'contrato_usuario', ['contrato_usuario_id'], ['id'])
    op.create_foreign_key(None, 'usuario_endereco', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_endereco', type_='foreignkey')
    op.drop_constraint(None, 'usuario_endereco', type_='foreignkey')
    op.drop_column('usuario_endereco', 'contrato_usuario_id')
    op.drop_column('usuario_endereco', 'usuario_id')
    # ### end Alembic commands ###
