"""empty message

Revision ID: 3a8bace32bf0
Revises: 
Create Date: 2021-08-12 12:46:06.074086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8bace32bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sobrenome', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=511), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_regristro', sa.Date(), nullable=False),
    sa.Column('e_pessoa_fisica', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('mae_nome', sa.String(length=150), nullable=True),
    sa.Column('pai_nome', sa.String(length=150), nullable=True),
    sa.Column('observacao', sa.String(length=511), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.Date(), nullable=True),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_nao_registrado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_nao_registrado')
    op.drop_table('usuario')
    # ### end Alembic commands ###
