"""empty message

Revision ID: 43d29499240f
Revises: 5b745ba7b744
Create Date: 2021-08-12 22:05:14.016623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d29499240f'
down_revision = '5b745ba7b744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('proposito', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico')
    # ### end Alembic commands ###
