"""empty message

Revision ID: 46d5f8c08eb4
Revises: 176202e126bc
Create Date: 2021-08-12 20:24:01.986426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d5f8c08eb4'
down_revision = '176202e126bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_comercial', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=150), nullable=True),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('wireless_login', sa.String(length=150), nullable=True),
    sa.Column('wireless_senha', sa.String(length=150), nullable=True),
    sa.Column('onu_login', sa.String(length=150), nullable=True),
    sa.Column('onu_senha', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_cliente', sa.Boolean(), nullable=True),
    sa.Column('e_representante', sa.Boolean(), nullable=True),
    sa.Column('e_funcionario', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_permissao')
    op.drop_table('usuario_endereco')
    # ### end Alembic commands ###
