"""empty message

Revision ID: 5b745ba7b744
Revises: 4e76a7ddb7b7
Create Date: 2021-08-12 21:42:36.444593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b745ba7b744'
down_revision = '4e76a7ddb7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('numero_serie', sa.String(length=150), nullable=False),
    sa.Column('estoque', sa.Float(), nullable=True),
    sa.Column('velocidade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('contrato_usuario')
    # ### end Alembic commands ###
