"""empty message

Revision ID: 5c4bfa781b10
Revises: 54f2815f39cd
Create Date: 2021-08-24 21:41:00.548392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4bfa781b10'
down_revision = '54f2815f39cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem_servico', sa.Column('finalizado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordem_servico', 'finalizado')
    # ### end Alembic commands ###
