"""empty message

Revision ID: 61454c551d4b
Revises: e2e8b69d2e74
Create Date: 2021-08-16 20:52:12.807257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61454c551d4b'
down_revision = 'e2e8b69d2e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimento', sa.Column('ordem_servico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atendimento', 'ordem_servico', ['ordem_servico_id'], ['id'])
    op.alter_column('produto_fornecedor', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('produto_fornecedor', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto_fornecedor', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produto_fornecedor', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'atendimento', type_='foreignkey')
    op.drop_column('atendimento', 'ordem_servico_id')
    # ### end Alembic commands ###
