"""empty message

Revision ID: 775672d6be9c
Revises: 43d29499240f
Create Date: 2021-08-12 22:19:06.421636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775672d6be9c'
down_revision = '43d29499240f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('duracao_estimada', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita_tecnica')
    # ### end Alembic commands ###
