"""empty message

Revision ID: 8465ca5e96d6
Revises: adeef08d281a
Create Date: 2021-08-12 22:50:04.214286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8465ca5e96d6'
down_revision = 'adeef08d281a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=150), nullable=False),
    sa.Column('complemento', sa.String(length=150), nullable=True),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor_endereco')
    # ### end Alembic commands ###
