"""empty message

Revision ID: 9df94c4fba3a
Revises: 1db118f5cf56
Create Date: 2021-08-15 20:02:26.446583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df94c4fba3a'
down_revision = '1db118f5cf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita_tecnica_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('visita_tecnica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['visita_tecnica_id'], ['visita_tecnica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('visita_tecnica', sa.Column('ordem_servico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visita_tecnica', 'ordem_servico', ['ordem_servico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visita_tecnica', type_='foreignkey')
    op.drop_column('visita_tecnica', 'ordem_servico_id')
    op.drop_table('visita_tecnica_tecnico')
    # ### end Alembic commands ###
