"""empty message

Revision ID: 9fa4958bec7e
Revises: 0fe86f182a1c
Create Date: 2021-08-15 19:25:30.757248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa4958bec7e'
down_revision = '0fe86f182a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar', sa.Column('fornecedor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contas_a_pagar', 'fornecedor', ['fornecedor_id'], ['id'])
    op.add_column('fornecedor', sa.Column('endereco_fornecedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fornecedor', 'fornecedor_endereco', ['endereco_fornecedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fornecedor', type_='foreignkey')
    op.drop_column('fornecedor', 'endereco_fornecedor_id')
    op.drop_constraint(None, 'contas_a_pagar', type_='foreignkey')
    op.drop_column('contas_a_pagar', 'fornecedor_id')
    # ### end Alembic commands ###
