"""empty message

Revision ID: a01333641394
Revises: a5dfd9787f71
Create Date: 2021-08-15 22:03:23.408808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01333641394'
down_revision = 'a5dfd9787f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_receber', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas_a_receber', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas_a_receber', type_='foreignkey')
    op.drop_column('contas_a_receber', 'usuario_id')
    # ### end Alembic commands ###
