"""empty message

Revision ID: a0964d7f68d5
Revises: c487d9eb8394
Create Date: 2021-08-30 23:20:08.762836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0964d7f68d5'
down_revision = 'c487d9eb8394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fornecedor', ['cnpj'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fornecedor', type_='unique')
    # ### end Alembic commands ###
