"""empty message

Revision ID: a0dcef3d68fb
Revises: a0964d7f68d5
Create Date: 2021-08-31 08:42:58.861856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dcef3d68fb'
down_revision = 'a0964d7f68d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar', sa.Column('data_pago', sa.DateTime(), nullable=True))
    op.drop_column('contas_a_pagar', 'pago')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar', sa.Column('pago', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('contas_a_pagar', 'data_pago')
    # ### end Alembic commands ###
