"""empty message

Revision ID: a33843e73d28
Revises: 
Create Date: 2021-08-27 00:06:14.480962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33843e73d28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=150), nullable=False),
    sa.Column('complemento', sa.String(length=150), nullable=True),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('velocidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('numero_serie', sa.String(length=150), nullable=True),
    sa.Column('estoque', sa.Float(), nullable=True),
    sa.Column('velocidade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_nao_registrado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('e_comercial', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('rua', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('usuario_permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_cliente', sa.Boolean(), nullable=True),
    sa.Column('e_representante', sa.Boolean(), nullable=True),
    sa.Column('e_funcionario', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('duracao_meses', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=16), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=9), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('endereco_fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_fornecedor_id'], ['fornecedor_endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sobrenome', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=511), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_regristro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_pessoa_fisica', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('mae_nome', sa.String(length=150), nullable=True),
    sa.Column('pai_nome', sa.String(length=150), nullable=True),
    sa.Column('observacao', sa.String(length=511), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.String(length=50), nullable=True),
    sa.Column('salt', sa.String(length=16), nullable=False),
    sa.Column('usuario_permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_permissao_id'], ['usuario_permissao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contas_a_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_digitado', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_a_pagar', sa.Date(), nullable=False),
    sa.Column('nfe', sa.String(length=150), nullable=True),
    sa.Column('n_documento', sa.String(length=150), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_a_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_a_pagar', sa.Date(), nullable=False),
    sa.Column('data_pago', sa.DateTime(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('valor_contrato', sa.Float(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('proposito', sa.String(length=511), nullable=True),
    sa.Column('descricao', sa.String(length=511), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=511), nullable=True),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('usuario_cpf', sa.String(length=11), nullable=True),
    sa.Column('usuario_telefone', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_comercial', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=150), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=150), nullable=True),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('wireless_login', sa.String(length=150), nullable=True),
    sa.Column('wireless_senha', sa.String(length=150), nullable=True),
    sa.Column('onu_login', sa.String(length=150), nullable=True),
    sa.Column('onu_senha', sa.String(length=150), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contrato_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_usuario_id'], ['contrato_usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('duracao_estimada', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnica_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('visita_tecnica_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['visita_tecnica_id'], ['visita_tecnica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnica_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('visita_tecnica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['visita_tecnica_id'], ['visita_tecnica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita_tecnica_tecnico')
    op.drop_table('visita_tecnica_produto')
    op.drop_table('visita_tecnica')
    op.drop_table('usuario_endereco')
    op.drop_table('atendimento')
    op.drop_table('produto_fornecedor')
    op.drop_table('ordem_servico')
    op.drop_table('contrato_usuario')
    op.drop_table('contas_a_receber')
    op.drop_table('contas_a_pagar')
    op.drop_table('usuario')
    op.drop_table('plano_produto')
    op.drop_table('fornecedor')
    op.drop_table('contrato')
    op.drop_table('usuario_permissao')
    op.drop_table('usuario_nao_registrado')
    op.drop_table('produto')
    op.drop_table('plano')
    op.drop_table('fornecedor_endereco')
    # ### end Alembic commands ###
