"""empty message

Revision ID: a5dfd9787f71
Revises: b8dd190ef433
Create Date: 2021-08-15 21:54:58.972168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5dfd9787f71'
down_revision = 'b8dd190ef433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('plano_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contrato', 'plano', ['plano_id'], ['id'])
    op.add_column('contrato_usuario', sa.Column('valor_contrato', sa.Float(), nullable=False))
    op.add_column('contrato_usuario', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('contrato_usuario', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('contrato_usuario', sa.Column('usuario_endereco_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contrato_usuario', 'contrato', ['contrato_id'], ['id'])
    op.create_foreign_key(None, 'contrato_usuario', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'contrato_usuario', 'usuario_endereco', ['usuario_endereco_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contrato_usuario', type_='foreignkey')
    op.drop_constraint(None, 'contrato_usuario', type_='foreignkey')
    op.drop_constraint(None, 'contrato_usuario', type_='foreignkey')
    op.drop_column('contrato_usuario', 'usuario_endereco_id')
    op.drop_column('contrato_usuario', 'usuario_id')
    op.drop_column('contrato_usuario', 'contrato_id')
    op.drop_column('contrato_usuario', 'valor_contrato')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_column('contrato', 'plano_id')
    # ### end Alembic commands ###
