"""empty message

Revision ID: adeef08d281a
Revises: 775672d6be9c
Create Date: 2021-08-12 22:38:03.125529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adeef08d281a'
down_revision = '775672d6be9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=16), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=9), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
