"""empty message

Revision ID: b0aedf91d46d
Revises: 4b1d9383aa39
Create Date: 2021-08-17 10:21:50.275929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0aedf91d46d'
down_revision = '4b1d9383aa39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contrato_usuario_usuario_endereco_id_fkey', 'contrato_usuario', type_='foreignkey')
    op.drop_column('contrato_usuario', 'usuario_endereco_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato_usuario', sa.Column('usuario_endereco_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('contrato_usuario_usuario_endereco_id_fkey', 'contrato_usuario', 'usuario_endereco', ['usuario_endereco_id'], ['id'])
    # ### end Alembic commands ###
