"""empty message

Revision ID: b8dd190ef433
Revises: 9df94c4fba3a
Create Date: 2021-08-15 20:07:07.292765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dd190ef433'
down_revision = '9df94c4fba3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem_servico', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ordem_servico', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_column('ordem_servico', 'usuario_id')
    # ### end Alembic commands ###
