"""empty message

Revision ID: bc8f2c510cab
Revises: a01333641394
Create Date: 2021-08-15 22:11:20.790264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8f2c510cab'
down_revision = 'a01333641394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('usuario_permissao_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuario', 'usuario_permissao', ['usuario_permissao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'usuario_permissao_id')
    # ### end Alembic commands ###
