"""empty message

Revision ID: c30afffac960
Revises: a0dcef3d68fb
Create Date: 2021-08-31 22:28:54.072699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30afffac960'
down_revision = 'a0dcef3d68fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_receber', 'pago')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_receber', sa.Column('pago', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
