"""empty message

Revision ID: c487d9eb8394
Revises: 33a29368f639
Create Date: 2021-08-30 23:18:33.946950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c487d9eb8394'
down_revision = '33a29368f639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fornecedor', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fornecedor', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
