"""empty message

Revision ID: d6d71d99eaea
Revises: 46d5f8c08eb4
Create Date: 2021-08-12 20:47:04.465233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d71d99eaea'
down_revision = '46d5f8c08eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('velocidade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('usuario', 'data_regristro',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'data_regristro',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('plano')
    # ### end Alembic commands ###
