"""empty message

Revision ID: e361796164c5
Revises: 1900c783879f
Create Date: 2021-08-17 08:25:08.329405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e361796164c5'
down_revision = '1900c783879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atendimento_atendente_id_fkey', 'atendimento', type_='foreignkey')
    op.drop_column('atendimento', 'atendente_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimento', sa.Column('atendente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('atendimento_atendente_id_fkey', 'atendimento', 'usuario', ['atendente_id'], ['id'])
    # ### end Alembic commands ###
